name: Help

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Webhook Notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"content": "Test"}' ${{secrets.TOKEN_HELP}}